Create Array

In [ ]:
#Create Arrays
import numpy as np
arr=np.random.randint(1,50,10)

In [ ]:
arr1=np.random.randint(5,20,9)
arr2=arr1.reshape(3,3)
arr2

array([[ 9, 13, 13],
       [10, 15, 10],
       [13, 15,  8]])

Array Dimensions

In [ ]:
arr.ndim

1

In [ ]:
arr2.ndim

2

In [ ]:
arr.shape

(10,)

In [ ]:
arr2.shape

(3, 3)

Reshaping


In [ ]:
arr3=arr2.reshape(-1)
arr3

array([ 9, 13, 13, 10, 15, 10, 13, 15,  8])

Indexing and Slicing

In [ ]:
arr2[1,2]

np.int64(10)

In [ ]:
arr2[:2,-2:]

array([[13, 13],
       [15, 10]])

In [ ]:
arr_=arr.reshape(-1)
arr_[0:4]

array([30,  1,  7, 11])

In [ ]:
arr_[::-1]

array([20, 45,  5, 12, 32, 45, 11,  7,  1, 30])

Array Operations


In [ ]:
arr1=np.arange(1,11)
print(arr)
print(arr1)

print(arr+arr1)
print(arr*arr1)
print(arr1-5)

[30  1  7 11 45 32 12  5 45 20]
[ 1  2  3  4  5  6  7  8  9 10]
[31  3 10 15 50 38 19 13 54 30]
[ 30   2  21  44 225 192  84  40 405 200]
[-4 -3 -2 -1  0  1  2  3  4  5]


Random Numeber Generation

In [ ]:
arr1=np.random.rand(5)
arr1

array([0.14850901, 0.32120828, 0.52009101, 0.03727486, 0.31243357])

In [ ]:
arr2=np.random.randint(-1,1,5)
arr2

array([-1,  0,  0,  0, -1])

Bonus


In [ ]:
n=int(input())
arr=np.random.randint(1,100,n*n)
arr1=arr.reshape(n,n)
print(arr1)
print(sum(sum(arr1)))

5
[[48 41 22 28 19]
 [53 88 46 78 95]
 [ 1 78 15 40 45]
 [17 60 19 37 49]
 [26 15 65 77 35]]
1097
